listener 1883

allow_anonymous false

plugin /usr/lib/mosquitto_dynamic_security.so
plugin_opt_config_file /mosquitto/config/dynamic-security.json

persistence true
persistence_location /mosquitto/data/
log_dest stdout
